apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: clinicos-destination
  namespace: default
spec:
  host: clinicos-service
  subsets:
  - name: stable
    labels:
      version: v1
  - name: canary
    labels:
      version: v2